### ISSUE TITLE
Oops, ignore this issue

### ISSUE THREAD

**Issue by rickbrew** [PackJC/Paint.NET-PAA-PAC-Importer#1]
Bah, never mind this, I posted to the wrong repo

**Comment by rickbrew** [comment]
FYI this is where I was trying to post it https://github.com/alexandre-lecoq/Unofficial.PaintDotNet.Binaries/issues/1 . Mixed up my tabs or something.

**Comment by PackJC** [comment]
@rickbrew I have upgraded the project to .NET 7 in respects to your point.
